import { ProductModel, TransactionModel, SystemLogModel } from "./types";

export const initialProducts: ProductModel[] = [
  {
    id: "prod-1",
    sku: "SKU-COR-001",
    name: "Industrial Copper Pipes 3\" (Case)",
    currentStock: 4,
    minRequiredStock: 12,
    purchasePrice: 125.0,
    retailPrice: 195.0,
    category: "Hardware",
  },
  {
    id: "prod-2",
    sku: "SKU-CAB-099",
    name: "Fibre Optic Roll 500m (Single)",
    currentStock: 18,
    minRequiredStock: 10,
    purchasePrice: 340.0,
    retailPrice: 499.0,
    category: "Cables",
  },
  {
    id: "prod-3",
    sku: "SKU-VAL-511",
    name: "Brass Pressure Valves M4",
    currentStock: 2,
    minRequiredStock: 8,
    purchasePrice: 42.5,
    retailPrice: 65.0,
    category: "Hardware",
  },
  {
    id: "prod-4",
    sku: "SKU-SEAL-80",
    name: "Heavy Duty Gutter Sealant (Box)",
    currentStock: 45,
    minRequiredStock: 20,
    purchasePrice: 18.0,
    retailPrice: 29.9,
    category: "Consumables",
  },
  {
    id: "prod-5",
    sku: "SKU-FIL-104",
    name: "High-Temp Air Filters Pro-6",
    currentStock: 5,
    minRequiredStock: 15,
    purchasePrice: 68.0,
    retailPrice: 110.0,
    category: "Filter Systems",
  },
];

export const initialTransactions: TransactionModel[] = [
  {
    id: "tx-1001",
    title: "Sale - Optic Cables to TechCorp",
    amount: 1497.00,
    type: "sale",
    category: "Cables",
    timestamp: "2026-06-19T14:30:00-07:00",
    referenceNumber: "INV-2026-881",
    loggedBy: "Sarah Jenkins (Manager)",
    paymentMethod: "Bank",
  },
  {
    id: "tx-1002",
    title: "Purchase - Bulk Brass Valves Supplier",
    amount: 850.00,
    type: "purchase",
    category: "Hardware",
    timestamp: "2026-06-19T11:15:00-07:00",
    referenceNumber: "PO-4099-01",
    loggedBy: "Alex Wong (Accountant)",
    paymentMethod: "Bank",
  },
  {
    id: "tx-1003",
    title: "Sale - Counter Walk-in Cash Hardware",
    amount: 325.00,
    type: "sale",
    category: "Hardware",
    timestamp: "2026-06-19T10:00:00-07:00",
    referenceNumber: "CS-2026-904",
    loggedBy: "Marcus Lane (Staff)",
    paymentMethod: "Cash",
  },
  {
    id: "tx-1004",
    title: "Expense - Warehouse Electrical Utility Bill",
    amount: 412.50,
    type: "expense",
    category: "Utilities",
    timestamp: "2026-06-18T16:45:00-07:00",
    referenceNumber: "EXP-UTIL-44",
    loggedBy: "Alex Wong (Accountant)",
    paymentMethod: "Bank",
  },
  {
    id: "tx-1005",
    title: "Sale - Export Consumables Order #129",
    amount: 897.00,
    type: "sale",
    category: "Consumables",
    timestamp: "2026-06-18T11:20:00-07:00",
    referenceNumber: "INV-2026-880",
    loggedBy: "Sarah Jenkins (Manager)",
    paymentMethod: "Mobile Pay",
  },
  {
    id: "tx-1006",
    title: "Expense - Logistics Shipping Fuel Reimb",
    amount: 185.00,
    type: "expense",
    category: "Fuel & Travel",
    timestamp: "2026-06-17T09:10:00-07:00",
    referenceNumber: "EXP-FUEL-909",
    loggedBy: "Marcus Lane (Staff)",
    paymentMethod: "Cash",
  },
];

export const initialLogs: SystemLogModel[] = [
  {
    id: "log-1",
    action: "ERP Bootstrapped",
    details: "System successfully loaded with Firebase Firestore and Google Workspace integration blueprint.",
    role: "admin",
    timestamp: "2026-06-19T08:00:22-07:00",
  },
  {
    id: "log-2",
    action: "Role-Based Access Synced",
    details: "Privilege tiers synchronized: Admin has complete override; accountant manages Ledger & General Journal.",
    role: "admin",
    timestamp: "2026-06-19T08:30:11-07:00",
  },
  {
    id: "log-3",
    action: "Low Stock Trigger",
    details: "Product SKU-COR-001 count dropped to 4 (threshold: 12). Suggested Action: Raise Purchase Order.",
    role: "manager",
    timestamp: "2026-06-19T14:31:05-07:00",
  },
];
